# DUCKDB

Since data from EuroCropsV2 is in duckdb format, i will try to load everything in a dataframe, analyze a portion of all the data that there is and then try to figure out how to concatenate with the satellites photos during a given timeframe eg. a year or so

Everything is downloaded from the next few code cells, python notebooks are used because it is easier to prototype python code here since i can inspect datastructures with ease

In [1]:
import duckdb
import datetime as dt
import sys

from EuroCropsV2.code.import_db.a00_main import *
from EuroCropsV2.code.utils.tools import global_config

start_time = '01-01-2021'
end_time = '31-12-2022'

print("USER:", os.environ.get("USER"))
print("HOME:", os.environ.get("HOME"))
print("expanduser:", os.path.expanduser("~"))
print("duckdb:", duckdb.__version__)

print("DuckDB:", duckdb.__version__)
print("DuckDB module:", duckdb.__file__)
print("Python:", sys.executable)
print("Currentdir: ", os.getcwd())

main(global_config, False, True, False)

USER: marcofagnani
HOME: /home/marcofagnani
expanduser: /home/marcofagnani
duckdb: 1.5.5
DuckDB: 1.5.5
DuckDB module: /home/marcofagnani/RSSIA-Project/.venv/lib/python3.10/site-packages/duckdb/__init__.py
Python: /home/marcofagnani/RSSIA-Project/.venv/bin/python
Currentdir:  /home/marcofagnani/RSSIA-Project
Importing files to DuckDB
Importing files to DuckDB
['/media/datapart/marcofagnani/dataset/es_stack.parquet', '/media/datapart/marcofagnani/dataset/ee_2020.parquet', '/media/datapart/marcofagnani/dataset/at_2020.parquet', '/media/datapart/marcofagnani/dataset/dea_stack.parquet', '/media/datapart/marcofagnani/dataset/fi_2020.parquet', '/media/datapart/marcofagnani/dataset/iti1_2020.parquet', '/media/datapart/marcofagnani/dataset/dk_2020.parquet', '/media/datapart/marcofagnani/dataset/de4_stack.parquet', '/media/datapart/marcofagnani/dataset/nl_2020.parquet', '/media/datapart/marcofagnani/dataset/bg_stack.parquet', '/media/datapart/marcofagnani/dataset/cz_stack.parquet', '/media/datapart/marcofagnani/dataset/sk_2020.parquet', '/media/datapart/marcofagnani/dataset/si_2020.parquet', '/media/datapart/marcofagnani/dataset/fi_stack.parquet', '/media/datapart/marcofagnani/dataset/ie_2020.parquet', '/media/datapart/marcofagnani/dataset/de4_2020.parquet', '/media/datapart/marcofagnani/dataset/dea_2020.parquet', '/media/datapart/marcofagnani/dataset/si_stack.parquet', '/media/datapart/marcofagnani/dataset/sk_stack.parquet', '/media/datapart/marcofagnani/dataset/dk_stack.parquet', '/media/datapart/marcofagnani/dataset/be2_stack.parquet', '/media/datapart/marcofagnani/dataset/pt_stack.parquet', '/media/datapart/marcofagnani/dataset/be3_stack.parquet', '/media/datapart/marcofagnani/dataset/fr_stack.parquet', '/media/datapart/marcofagnani/dataset/be2_2020.parquet', '/media/datapart/marcofagnani/dataset/iti1_stack.parquet', '/media/datapart/marcofagnani/dataset/be3_2020.parquet', '/media/datapart/marcofagnani/dataset/nl_stack.parquet', '/media/datapart/marcofagnani/dataset/at_stack.parquet', '/media/datapart/marcofagnani/dataset/bg_2020.parquet', '/media/datapart/marcofagnani/dataset/ie_stack.parquet', '/media/datapart/marcofagnani/dataset/de4_stack_bu.parquet', '/media/datapart/marcofagnani/dataset/fr_2020.parquet', '/media/datapart/marcofagnani/dataset/ee_stack.parquet', '/media/datapart/marcofagnani/dataset/pt_2020.parquet']
Adding file to upload: /media/datapart/marcofagnani/dataset/es_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/ee_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/at_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/dea_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/fi_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/iti1_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/dk_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/de4_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/nl_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/bg_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/cz_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/sk_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/si_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/fi_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/ie_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/de4_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/dea_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/si_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/sk_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/dk_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/be2_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/pt_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/be3_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/fr_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/be2_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/iti1_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/be3_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/nl_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/at_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/bg_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/ie_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/de4_stack_bu.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/fr_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/ee_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/pt_2020.parquet
['es_stack', 'ee_2020', 'at_2020', 'dea_stack', 'fi_2020', 'iti1_2020', 'dk_2020', 'de4_stack', 'nl_2020', 'bg_stack', 'cz_stack', 'sk_2020', 'si_2020', 'fi_stack', 'ie_2020', 'de4_2020', 'dea_2020', 'si_stack', 'sk_stack', 'dk_stack', 'be2_stack', 'pt_stack', 'be3_stack', 'fr_stack', 'be2_2020', 'iti1_stack', 'be3_2020', 'nl_stack', 'at_stack', 'bg_2020', 'ie_stack', 'de4_stack_bu', 'fr_2020', 'ee_stack', 'pt_2020']
/media/datapart/marcofagnani/dataset/es_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/ee_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/at_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/dea_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/fi_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/iti1_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/dk_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/de4_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/nl_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/bg_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/cz_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/sk_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/si_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/fi_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/ie_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/de4_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/dea_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/si_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/sk_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/dk_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/be2_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/pt_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/be3_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/fr_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/be2_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/iti1_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/be3_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/nl_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/at_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/bg_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/ie_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/de4_stack_bu.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/fr_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/ee_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/pt_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

-----> exec time = 33.07mn
Importing mapping tables to DuckDB

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

DuckDB table 'eurocrops' written using native API.

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

DuckDB table 'hcat4_agriprod_mapping' written using native API.

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

DuckDB table 'hcat4_eagle_mapping' written using native API.

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

DuckDB table 'hcat4_hrl_mapping' written using native API.

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

DuckDB table 'agriprod_fadn_mapping' written using native API.

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

DuckDB table 'hcat4' written using native API.
-----> exec time = 0.01mn

In [ ]:
# import tempfile
# tempfile.tempdir = '/scratch/clamart/'

# import json
import duckdb
import datetime as dt
import ipywidgets

RunDownload  = True
RunImportDuckDB = True
RunImportPGDB = False



# 

import os
from EuroCropsV2.code.utils.tools import global_config

# import pdb;set_trace()

os.makedirs(os.path.dirname(os.path.abspath(global_config.paths['duckdbpath'])), exist_ok=True)

# dd
def main(global_config):
    if RunDownload:
        print("Downloading files from FTP")
        from EuroCropsV2.code.import_db.a01_download_from_ftp import download as download_from_ftp
        download_from_ftp(global_config)
    if RunImportDuckDB:
        print("Importing files to DuckDB")
        from EuroCropsV2.code.import_db.a02_import_to_duckdb import upload as import_to_duckdb
        import_to_duckdb(global_config)
    if RunImportPGDB:
        print("Importing files to PostgreSQL/PostGIS")
        from EuroCropsV2.code.import_db.a03_import_to_pgdb import upload as import_to_pgdb
        import_to_pgdb(global_config)
        # run 04_update_mapping_tables.py
        # run 05_Create_GSA_all_view_layers.py
        # run 06_create_gsa_crop_grid_2.py
    


main(global_config)

In [3]:
conn = duckdb.connect(global_config.paths['duckdbpath'])

tables_df = conn.execute("SHOW TABLES").fetchdf()
print(tables_df)

                      name
0    agriprod_fadn_mapping
1                  at_2020
2                 at_stack
3                 be2_2020
4                be2_stack
5                 be3_2020
6                be3_stack
7                  bg_2020
8                 bg_stack
9                 cz_stack
10                de4_2020
11               de4_stack
12            de4_stack_bu
13                dea_2020
14               dea_stack
15                 dk_2020
16                dk_stack
17                 ee_2020
18                ee_stack
19                es_stack
20               eurocrops
21                 fi_2020
22                fi_stack
23                 fr_2020
24                fr_stack
25                   hcat4
26  hcat4_agriprod_mapping
27     hcat4_eagle_mapping
28       hcat4_hrl_mapping
29                 ie_2020
30                ie_stack
31               iti1_2020
32              iti1_stack
33                 nl_2020
34                nl_stack
35                 pt_2020
36                pt_stack
37                 si_2020
38                si_stack
39                 sk_2020
40                sk_stack

In [4]:
conn.execute("SELECT * FROM agriprod_fadn_mapping").fetch_df()

,agriprod_code,agriprod_name,fadn_code,code_name
0,ARA,Arable land,SE026,Arable land (ha)
1,C0000,Cereals for the production of grain (including...,SE035,Cereals (ha)
2,C1000,Cereals (excluding rice) for the production of...,SE035,Cereals (ha)
3,C1110,Common wheat and spelt,SE035,Cereals (ha)
4,C1111,Common winter wheat and spelt,SE035,Cereals (ha)
...,...,...,...,...
183,W1000,Grapes,SE050,Vineyards (ha)
184,W1100,Grapes for wines,SE050,Vineyards (ha)
185,W1200,Grapes for table use,SE050,Vineyards (ha)
186,W1300,Grapes for raisins,SE050,Vineyards (ha)
187,WA,Wooded areas,SE075,Woodland area (ha)

In [7]:

conn.execute("SET enable_geoparquet_conversion = false;")


test = conn.execute("SET enable_geoparquet_conversion = false; SELECT * FROM eurocrops " \
"INNER JOIN hcat4 on eurocrops.hcat4_code = hcat4.hcat4_code " \
"INNER JOIN hcat4_agriprod_mapping as hcat4_am on eurocrops.hcat4_code = hcat4_am.hcat4_code " \
"INNER JOIN hcat4_eagle_mapping as hcat4_em on eurocrops.hcat4_code = hcat4_em.hcat4_code " \
"INNER JOIN hcat4_hrl_mapping as hcat4_hrl on eurocrops.hcat4_code = hcat4_hrl.hcat4_code " \
"INNER JOIN agriprod_fadn_mapping as agfm on hcat4_am.agriprod_code = agfm.agriprod_code").fetch_df()

In [9]:
test

,nuts,original_code,original_name,translated_name,hcat4_code,hcat4_name,usage_code,usage_name,hcat4_code_1,hcat4_name_1,...,eagle_seasonality_code,eagle_seasonality_name,hcat4_code_4,hcat4_name_4,hrl_code,hrl_name,agriprod_code_1,agriprod_name_1,fadn_code,code_name
0,at,10001,NICHT DEFINIERT,not defined,3390000000,not_known_and_other,0,No specified use,3390000000,not_known_and_other,...,None,None,3390000000,not_known_and_other,0,Other,FA9,Other areas on the farms,None,None
1,at,105,KÖRNERMAIS,GRAIN CORN,3310106000,maize_corn_popcorn,6,Harvested as Grains,3310106000,maize_corn_popcorn,...,None,None,3310106000,maize_corn_popcorn,1130,Maize,C1500,Grain maize and corn-cob-mix,SE035,Cereals (ha)
2,at,106,MAIS CORN-COB-MIX (CCM),CORN CORN-COB-MIX (CCM),3310106000,maize_corn_popcorn,0,No specified use,3310106000,maize_corn_popcorn,...,None,None,3310106000,maize_corn_popcorn,1130,Maize,C1500,Grain maize and corn-cob-mix,SE035,Cereals (ha)
3,at,107,ZUCKERMAIS,SUGAR CORN,3310106000,maize_corn_popcorn,0,No specified use,3310106000,maize_corn_popcorn,...,None,None,3310106000,maize_corn_popcorn,1130,Maize,C1500,Grain maize and corn-cob-mix,SE035,Cereals (ha)
4,at,109,SILOMAIS,SILO CORN,3310106000,maize_corn_popcorn,3,Fodder/Forage,3310106000,maize_corn_popcorn,...,None,None,3310106000,maize_corn_popcorn,1130,Maize,C1500,Grain maize and corn-cob-mix,SE035,Cereals (ha)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15109,sk,10152,Pôda ležiaca úhorom s porastom,Fallen land with vegetation,3311100000,fallow_land_not_crop,0,No specified use,3311100000,fallow_land_not_crop,...,None,None,3311100000,fallow_land_not_crop,3100,Unclassified arable crop,Q0000,Fallow land,SE073,Set aside (ha)
15110,sk,10153,Pôda ležiaca úhorom s produkciou bez hnojenia,Fallow land with production without fertilization,3311100000,fallow_land_not_crop,0,No specified use,3311100000,fallow_land_not_crop,...,None,None,3311100000,fallow_land_not_crop,3100,Unclassified arable crop,Q0000,Fallow land,SE073,Set aside (ha)
15111,sk,10154,Pôda ležiaca úhorom s produkciou s hnojením,Fallow land with production and fertilization,3311100000,fallow_land_not_crop,0,No specified use,3311100000,fallow_land_not_crop,...,None,None,3311100000,fallow_land_not_crop,3100,Unclassified arable crop,Q0000,Fallow land,SE073,Set aside (ha)
15112,sk,10197,Strukovinovo-obilná miešanka,Legume-cereal mixer,3310200000,legumes,0,No specified use,3310200000,legumes,...,None,None,3310200000,legumes,1220,Dry Pulses,P0000,Dry pulses and protein crops for the productio...,SE041,Other field crops (ha)
15113,sk,10198,Strukovinovo-olejná miešanka,Legume-oil mixer,3310200000,legumes,8,Oil,3310200000,legumes,...,None,None,3310200000,legumes,1220,Dry Pulses,P0000,Dry pulses and protein crops for the productio...,SE041,Other field crops (ha)

In [8]:
test.columns.values

array(['nuts', 'original_code', 'original_name', 'translated_name',
       'hcat4_code', 'hcat4_name', 'usage_code', 'usage_name',
       'hcat4_code_1', 'hcat4_name_1', 'seasonality_code',
       'seasonality_name', 'hcat4_code_2', 'hcat4_name_2', 'usage_code_1',
       'usage_name_1', 'link', 'agriprod_code', 'agriprod_name',
       'hcat4_code_3', 'hcat4_name_3', 'link_1', 'eagle_code',
       'eagle_name', 'eagle_seasonality_code', 'eagle_seasonality_name',
       'hcat4_code_4', 'hcat4_name_4', 'hrl_code', 'hrl_name',
       'agriprod_code_1', 'agriprod_name_1', 'fadn_code', 'code_name'],
      dtype=object)

In [ ]:
conn = duckdb.connect(global_config.paths["duckdbpath"])

tables = conn.execute("SHOW TABLES").fetchdf()
print(tables)

In [ ]:
conn_shady = duckdb.connect('/home/wr3nch/Documents/Projects/RSSIA/dataset/exported/eurocropsv2.duckdb')

conn_shady.execute("SHOW TABLES").fetch_df()

In [ ]:
import duckdb

file_path = (
    "/home/wr3nch/Documents/Projects/RSSIA/"
    "dataset/at_2020.parquet"
)

conn = duckdb.connect()

conn.execute("SET enable_geoparquet_conversion = false;")

df = conn.execute("""
    SELECT *
    FROM read_parquet(?)
    LIMIT 10
""", [file_path]).fetchdf()

df

# AI Generated code
This section contains ai generated code because i don't get how the geometry (lat and long) is not loaded by their scripts but it is actually present in the parquet files.

In [ ]:
from pathlib import Path
import duckdb
import pandas as pd


# ------------------------------------------------------------------
# 1. Paths and table name
# ------------------------------------------------------------------

parquet_path = Path(
    "/home/wr3nch/Documents/Projects/RSSIA/dataset/at_2020.parquet"
)

duckdb_path = Path(
    "/home/wr3nch/Documents/Projects/RSSIA/dataset/eurocrops.duckdb"
)

table_name = "at_2020"


# ------------------------------------------------------------------
# 2. Validate paths
# ------------------------------------------------------------------

if not parquet_path.exists():
    raise FileNotFoundError(
        f"Parquet file does not exist:\n{parquet_path}"
    )

duckdb_path.parent.mkdir(parents=True, exist_ok=True)

print("Parquet file:", parquet_path)
print("DuckDB file:", duckdb_path)
print("DuckDB table:", table_name)


# ------------------------------------------------------------------
# 3. Open DuckDB
# ------------------------------------------------------------------

conn = duckdb.connect(str(duckdb_path))


# ------------------------------------------------------------------
# 4. Load the spatial extension
# ------------------------------------------------------------------

try:
    conn.execute("LOAD spatial")
except duckdb.Error:
    # INSTALL requires internet only if the extension is not already installed.
    conn.execute("INSTALL spatial")
    conn.execute("LOAD spatial")


# ------------------------------------------------------------------
# 5. Disable automatic GeoParquet conversion
#
# The EuroCropsV2 files can contain incomplete GeoParquet metadata.
# With conversion disabled, geometry is read as raw WKB/BLOB.
# ------------------------------------------------------------------

conn.execute("""
    SET enable_geoparquet_conversion = false
""")


# ------------------------------------------------------------------
# 6. Inspect the raw Parquet schema
# ------------------------------------------------------------------

raw_schema = conn.execute(
    """
    DESCRIBE
    SELECT *
    FROM read_parquet(?)
    """,
    [str(parquet_path)],
).fetchdf()

print("\nRaw Parquet schema:")
display(raw_schema)


# ------------------------------------------------------------------
# 7. Verify that the geometry column exists
# ------------------------------------------------------------------

raw_columns = set(raw_schema["column_name"].str.lower())

if "geometry" not in raw_columns:
    raise RuntimeError(
        "The Parquet file does not contain a column named 'geometry'. "
        f"Available columns: {sorted(raw_columns)}"
    )


# ------------------------------------------------------------------
# 8. Import the Parquet file into DuckDB
# ------------------------------------------------------------------

conn.execute(
    f"""
    CREATE OR REPLACE TABLE "{table_name}" AS
    SELECT *
    FROM read_parquet(?)
    """,
    [str(parquet_path)],
)

print(f"\nImported {parquet_path.name} into table {table_name!r}")


# ------------------------------------------------------------------
# 9. Convert raw WKB geometry to DuckDB GEOMETRY
# ------------------------------------------------------------------

conn.execute(
    f"""
    ALTER TABLE "{table_name}"
    ADD COLUMN geom GEOMETRY
    """
)

conn.execute(
    f"""
    UPDATE "{table_name}"
    SET geom = ST_GeomFromWKB(geometry)
    WHERE geometry IS NOT NULL
    """
)


# ------------------------------------------------------------------
# 10. Remove the original raw WKB column
#
# Comment this section out if you want to preserve both geometry and geom.
# ------------------------------------------------------------------

conn.execute(
    f"""
    ALTER TABLE "{table_name}"
    DROP COLUMN geometry
    """
)


# ------------------------------------------------------------------
# 11. Create a spatial index
# ------------------------------------------------------------------

conn.execute(
    f"""
    CREATE INDEX IF NOT EXISTS "{table_name}_geom_rtree"
    ON "{table_name}"
    USING RTREE (geom)
    """
)


# ------------------------------------------------------------------
# 12. Verify the imported table
# ------------------------------------------------------------------

imported_schema = conn.execute(
    f'DESCRIBE "{table_name}"'
).fetchdf()

print("\nImported DuckDB schema:")
display(imported_schema)

row_count = conn.execute(
    f'SELECT COUNT(*) FROM "{table_name}"'
).fetchone()[0]

geometry_count = conn.execute(
    f"""
    SELECT COUNT(*)
    FROM "{table_name}"
    WHERE geom IS NOT NULL
    """
).fetchone()[0]

print("\nTotal rows:", row_count)
print("Rows with geometry:", geometry_count)


# ------------------------------------------------------------------
# 13. Check geometry types
# ------------------------------------------------------------------

geometry_types = conn.execute(
    f"""
    SELECT
        ST_GeometryType(geom) AS geometry_type,
        COUNT(*) AS row_count
    FROM "{table_name}"
    WHERE geom IS NOT NULL
    GROUP BY ST_GeometryType(geom)
    ORDER BY row_count DESC
    """
).fetchdf()

print("\nGeometry types:")
display(geometry_types)


# ------------------------------------------------------------------
# 14. Derive longitude and latitude
#
# EuroCropsV2 geometry is expected to use EPSG:3035.
#
# ST_PointOnSurface returns a representative point guaranteed to lie
# inside the parcel. The point is then transformed to EPSG:4326.
#
# X = longitude
# Y = latitude
# ------------------------------------------------------------------

coordinate_query = f"""
WITH representative_points AS (
    SELECT
        *,
        ST_PointOnSurface(geom) AS point_3035
    FROM "{table_name}"
    WHERE geom IS NOT NULL
),

wgs84_points AS (
    SELECT
        *,
        ST_Transform(
            point_3035,
            'EPSG:3035',
            'EPSG:4326',
            always_xy := true
        ) AS point_wgs84
    FROM representative_points
)

SELECT
    * EXCLUDE (point_3035, point_wgs84),

    ST_X(point_wgs84) AS longitude,
    ST_Y(point_wgs84) AS latitude

FROM wgs84_points
"""

df = conn.execute(coordinate_query).fetchdf()


# ------------------------------------------------------------------
# 15. Inspect the resulting Pandas DataFrame
# ------------------------------------------------------------------

print("\nDataFrame shape:", df.shape)
display(df.head())

print("\nCoordinate sample:")
display(
    df[["longitude", "latitude"]]
    .dropna()
    .head(10)
)


# ------------------------------------------------------------------
# 16. Basic coordinate sanity check
# ------------------------------------------------------------------

invalid_coordinates = df[
    ~df["longitude"].between(-180, 180)
    | ~df["latitude"].between(-90, 90)
]

print("\nRows with invalid longitude/latitude:", len(invalid_coordinates))


# ------------------------------------------------------------------
# 17. Optional: export the result to Parquet
# ------------------------------------------------------------------

output_path = parquet_path.with_name("at_2020_with_coordinates.parquet")

conn.execute(
    f"""
    COPY (
        {coordinate_query}
    )
    TO ?
    (
        FORMAT PARQUET,
        COMPRESSION ZSTD
    )
    """,
    [str(output_path)],
)

print("\nOutput written to:", output_path)


# ------------------------------------------------------------------
# 18. Show all tables currently in the DuckDB database
# ------------------------------------------------------------------

print("\nDuckDB tables:")
display(conn.execute("SHOW TABLES").fetchdf())


# Close only when you have finished querying the database.
# conn.close()