# DUCKDB

Since data from EuroCropsV2 is in duckdb format, i will try to load everything in a dataframe, analyze a portion of all the data that there is and then try to figure out how to concatenate with the satellites photos during a given timeframe eg. a year or so

Everything is downloaded from the next few code cells, python notebooks are used because it is easier to prototype python code here since i can inspect datastructures with ease

In [1]:
import duckdb
import datetime as dt
import sys

from EuroCropsV2.code.import_db.a00_main import *
from EuroCropsV2.code.utils.tools import global_config

start_time = '01-01-2021'
#end_time = '31-12-2022'
end_time = '01-02-2021'

print("USER:", os.environ.get("USER"))
print("HOME:", os.environ.get("HOME"))
print("expanduser:", os.path.expanduser("~"))
print("duckdb:", duckdb.__version__)

print("DuckDB:", duckdb.__version__)
print("DuckDB module:", duckdb.__file__)
print("Python:", sys.executable)
print("Currentdir: ", os.getcwd())

main(global_config, False, True, False)

USER: marcofagnani
HOME: /home/marcofagnani
expanduser: /home/marcofagnani
duckdb: 1.5.5
DuckDB: 1.5.5
DuckDB module: /home/marcofagnani/RSSIA-Project/.miniconda/envs/rssia/lib/python3.11/site-packages/duckdb/__init__.py
Python: /home/marcofagnani/RSSIA-Project/.miniconda/envs/rssia/bin/python
Currentdir:  /home/marcofagnani/RSSIA-Project
Importing files to DuckDB
Importing files to DuckDB
['/media/datapart/marcofagnani/dataset/ie_stack.parquet', '/media/datapart/marcofagnani/dataset/bg_stack.parquet', '/media/datapart/marcofagnani/dataset/nl_stack.parquet', '/media/datapart/marcofagnani/dataset/dk_2020.parquet', '/media/datapart/marcofagnani/dataset/dk_stack.parquet', '/media/datapart/marcofagnani/dataset/nl_2020.parquet', '/media/datapart/marcofagnani/dataset/ee_stack.parquet', '/media/datapart/marcofagnani/dataset/ie_2020.parquet', '/media/datapart/marcofagnani/dataset/at_2020.parquet', '/media/datapart/marcofagnani/dataset/es_stack.parquet', '/media/datapart/marcofagnani/dataset/pt_2020.parquet', '/media/datapart/marcofagnani/dataset/si_stack.parquet', '/media/datapart/marcofagnani/dataset/de4_2020.parquet', '/media/datapart/marcofagnani/dataset/pt_stack.parquet', '/media/datapart/marcofagnani/dataset/be3_stack.parquet', '/media/datapart/marcofagnani/dataset/sk_2020.parquet', '/media/datapart/marcofagnani/dataset/be2_stack.parquet', '/media/datapart/marcofagnani/dataset/fr_stack.parquet', '/media/datapart/marcofagnani/dataset/si_2020.parquet', '/media/datapart/marcofagnani/dataset/fr_2020.parquet', '/media/datapart/marcofagnani/dataset/cz_stack.parquet', '/media/datapart/marcofagnani/dataset/sk_stack.parquet', '/media/datapart/marcofagnani/dataset/fi_2020.parquet', '/media/datapart/marcofagnani/dataset/dea_2020.parquet', '/media/datapart/marcofagnani/dataset/ee_2020.parquet', '/media/datapart/marcofagnani/dataset/be2_2020.parquet', '/media/datapart/marcofagnani/dataset/de4_stack_bu.parquet', '/media/datapart/marcofagnani/dataset/at_stack.parquet', '/media/datapart/marcofagnani/dataset/fi_stack.parquet', '/media/datapart/marcofagnani/dataset/be3_2020.parquet', '/media/datapart/marcofagnani/dataset/iti1_2020.parquet', '/media/datapart/marcofagnani/dataset/de4_stack.parquet', '/media/datapart/marcofagnani/dataset/dea_stack.parquet', '/media/datapart/marcofagnani/dataset/iti1_stack.parquet', '/media/datapart/marcofagnani/dataset/bg_2020.parquet']
Adding file to upload: /media/datapart/marcofagnani/dataset/ie_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/bg_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/nl_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/dk_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/dk_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/nl_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/ee_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/ie_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/at_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/es_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/pt_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/si_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/de4_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/pt_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/be3_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/sk_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/be2_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/fr_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/si_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/fr_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/cz_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/sk_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/fi_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/dea_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/ee_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/be2_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/de4_stack_bu.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/at_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/fi_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/be3_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/iti1_2020.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/de4_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/dea_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/iti1_stack.parquet
Adding file to upload: /media/datapart/marcofagnani/dataset/bg_2020.parquet
['ie_stack', 'bg_stack', 'nl_stack', 'dk_2020', 'dk_stack', 'nl_2020', 'ee_stack', 'ie_2020', 'at_2020', 'es_stack', 'pt_2020', 'si_stack', 'de4_2020', 'pt_stack', 'be3_stack', 'sk_2020', 'be2_stack', 'fr_stack', 'si_2020', 'fr_2020', 'cz_stack', 'sk_stack', 'fi_2020', 'dea_2020', 'ee_2020', 'be2_2020', 'de4_stack_bu', 'at_stack', 'fi_stack', 'be3_2020', 'iti1_2020', 'de4_stack', 'dea_stack', 'iti1_stack', 'bg_2020']
/media/datapart/marcofagnani/dataset/ie_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/bg_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/nl_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/dk_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/dk_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/nl_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/ee_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/ie_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/at_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/es_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/pt_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/si_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/de4_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/pt_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/be3_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/sk_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/be2_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/fr_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/si_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/fr_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/cz_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/sk_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/fi_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/dea_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/ee_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/be2_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/de4_stack_bu.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/at_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/fi_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/be3_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/iti1_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/de4_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/dea_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/iti1_stack.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

/media/datapart/marcofagnani/dataset/bg_2020.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

-----> exec time = 22.23mn
Importing mapping tables to DuckDB

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

DuckDB table 'eurocrops' written using native API.
DuckDB table 'hcat4_agriprod_mapping' written using native API.
DuckDB table 'hcat4_eagle_mapping' written using native API.
DuckDB table 'hcat4_hrl_mapping' written using native API.
DuckDB table 'agriprod_fadn_mapping' written using native API.
DuckDB table 'hcat4' written using native API.
-----> exec time = 0.00mn

In [1]:
import duckdb
from EuroCropsV2.code.utils.tools import global_config


conn = duckdb.connect(global_config.paths['duckdbpath'])
conn.execute("LOAD SPATIAL;")


tables_df = conn.execute("SHOW TABLES").fetchdf()
print(tables_df)

#conn.execute("SHOW TABLES from eurocropsv2").fetch_df()

                      name
0    agriprod_fadn_mapping
1                  at_2020
2                 at_stack
3                 be2_2020
4                be2_stack
5                 be3_2020
6                be3_stack
7                  bg_2020
8                 bg_stack
9                 cz_stack
10                de4_2020
11               de4_stack
12            de4_stack_bu
13                dea_2020
14               dea_stack
15                 dk_2020
16                dk_stack
17                 ee_2020
18                ee_stack
19                es_stack
20               eurocrops
21                 fi_2020
22                fi_stack
23                 fr_2020
24                fr_stack
25                   hcat4
26  hcat4_agriprod_mapping
27     hcat4_eagle_mapping
28       hcat4_hrl_mapping
29                 ie_2020
30                ie_stack
31               iti1_2020
32              iti1_stack
33                 nl_2020
34                nl_stack
35                 pt_2020
36                pt_stack
37                 si_2020
38                si_stack
39                 sk_2020
40                sk_stack

In [2]:
import re

for t in tables_df['name']:
    print(t)

agriprod_fadn_mapping
at_2020
at_stack
be2_2020
be2_stack
be3_2020
be3_stack
bg_2020
bg_stack
cz_stack
de4_2020
de4_stack
de4_stack_bu
dea_2020
dea_stack
dk_2020
dk_stack
ee_2020
ee_stack
es_stack
eurocrops
fi_2020
fi_stack
fr_2020
fr_stack
hcat4
hcat4_agriprod_mapping
hcat4_eagle_mapping
hcat4_hrl_mapping
ie_2020
ie_stack
iti1_2020
iti1_stack
nl_2020
nl_stack
pt_2020
pt_stack
si_2020
si_stack
sk_2020
sk_stack

In [4]:
conn.execute("select * from ee_stack").df()[:5].columns

Index(['cf2015', 'cf2016', 'cf2017', 'cf2018', 'cf2019', 'cf2020', 'cf2021',
       'cf2022', 'cf2023', 'c2015', 'c2016', 'c2017', 'c2018', 'c2019',
       'c2020', 'c2021', 'c2022', 'c2023', 'cropfield', 'area_ha', 'geom'],
      dtype='object')

In [11]:
conn.execute("select * from ee_2020").df().columns

Index(['cropfield', 'original_code', 'off_id', 'off_area', 'area_ha', 'geom'], dtype='object')

In [4]:
# Convert code to make it so that you can aggregate partial data on every cycle, convert columns name and drop columns,
# get the needed columns and save partial data ok disk without geospatial data for now

test = conn.execute("select * " \
"from hcat4 as h4 " \
"join eurocrops as e on h4.hcat4_code = e.hcat4_code"\
" join hcat4_agriprod_mapping as h4a on h4a.hcat4_code = h4.hcat4_code" \
" join hcat4_hrl_mapping as h4hrl on h4hrl.hcat4_code = h4.hcat4_code" \
" join ee_2020 as repo on repo.original_code = e.original_code").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [5]:
test.columns

Index(['hcat4_code', 'hcat4_name', 'seasonality_code', 'seasonality_name',
       'nuts', 'original_code', 'original_name', 'translated_name',
       'hcat4_code_1', 'hcat4_name_1', 'usage_code', 'usage_name',
       'hcat4_code_2', 'hcat4_name_2', 'usage_code_1', 'usage_name_1', 'link',
       'agriprod_code', 'agriprod_name', 'hcat4_code_3', 'hcat4_name_3',
       'hrl_code', 'hrl_name', 'cropfield', 'original_code_1', 'off_id',
       'off_area', 'area_ha', 'geom'],
      dtype='object')

In [24]:
conn.execute("select * from ee_2020").df()

,cropfield,original_code,off_id,off_area,area_ha,geom
0,174767,10074,19592173,3.18,3.175462,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 2, ..."
1,62797,10313,19454541,10.82,10.815301,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 4, ..."
2,63208,10055,19395769,2.43,2.430142,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
3,62800,10199,19454544,1.48,1.480860,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 3, ..."
4,62822,10251,19458345,3.17,3.172378,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
...,...,...,...,...,...,...
175946,113048,10056,17991578,2.98,2.981272,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
175947,113587,10056,17951340,3.12,3.122426,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
175948,13572,10199,18624422,5.97,5.971198,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 2, ..."
175949,15764,10199,18658543,1.25,1.253304,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
175950,13468,10228,18742757,3.59,3.585844,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."

In [12]:
tables = [
    "ee_2020",
    "eurocrops",
    "hcat4",
    "hcat4_agriprod_mapping",
    "hcat4_hrl_mapping",
]

for table in tables:
    print(f"\n===== {table} =====")

    query = f"""
    SELECT *
    FROM {table}
    LIMIT 5;
    """

    df = conn.execute(query).df()
    print(df.to_string())

===== ee_2020 =====
   cropfield original_code    off_id  off_area    area_ha                                                                                                                                                                                                                                                                                                                                                                                                                                         geom
0     174767         10074  19592173      3.18   3.175462          [1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 2, 0, 0, 0, 89, 0, 0, 0, 150, 7, 60, 53, 122, 57, 84, 65, 246, 110, 214, 175, 109, 136, 78, 65, 223, 28, 237, 27, 122, 57, 84, 65, 144, 98, 48, 187, 106, 136, 78, 65, 18, 33, 46, 20, 122, 57, 84, 65, 87, 234, 0, 76, 105, 136, 78, 65, 153, 247, 86, 5, 122, 57, 84, 65, 172, 221, 101, 226, 103, 136, 78, 65, 245, 187, 195, 167, 121, 57, 84, 65, 220, 218, 46, 183, 100, 136, ...]
1      62797         10313  19454541     10.82  10.815301               [1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 4, 0, 0, 0, 24, 0, 0, 0, 11, 37, 50, 82, 145, 252, 83, 65, 221, 201, 213, 222, 23, 139, 79, 65, 216, 12, 60, 152, 145, 252, 83, 65, 54, 225, 211, 179, 23, 139, 79, 65, 112, 10, 89, 88, 146, 252, 83, 65, 178, 104, 27, 9, 23, 139, 79, 65, 0, 186, 29, 178, 146, 252, 83, 65, 26, 192, 154, 74, 22, 139, 79, 65, 67, 94, 62, 9, 147, 252, 83, 65, 237, 79, 126, 46, 22, 139, ...]
2      63208         10055  19395769      2.43   2.430142       [1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, 0, 0, 0, 58, 0, 0, 0, 144, 219, 207, 226, 116, 70, 84, 65, 3, 63, 13, 109, 154, 119, 78, 65, 82, 105, 149, 142, 115, 70, 84, 65, 114, 40, 118, 163, 153, 119, 78, 65, 66, 32, 163, 179, 114, 70, 84, 65, 130, 176, 104, 181, 152, 119, 78, 65, 4, 148, 31, 154, 114, 70, 84, 65, 144, 150, 43, 140, 152, 119, 78, 65, 139, 71, 130, 65, 106, 70, 84, 65, 29, 14, 39, 122, 123, 119, ...]
3      62800         10199  19454544      1.48   1.480860  [1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 3, 0, 0, 0, 101, 0, 0, 0, 194, 253, 163, 211, 192, 252, 83, 65, 16, 182, 40, 163, 228, 140, 79, 65, 9, 5, 129, 255, 191, 252, 83, 65, 209, 226, 226, 175, 225, 140, 79, 65, 153, 221, 206, 0, 192, 252, 83, 65, 212, 244, 67, 208, 222, 140, 79, 65, 91, 21, 133, 14, 191, 252, 83, 65, 147, 128, 214, 47, 222, 140, 79, 65, 24, 62, 13, 198, 189, 252, 83, 65, 225, 56, 70, 237, 221, 140, ...]
4      62822         10251  19458345      3.17   3.172378    [1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, 0, 0, 0, 89, 0, 0, 0, 42, 123, 145, 225, 2, 182, 83, 65, 162, 163, 220, 188, 54, 114, 79, 65, 250, 172, 117, 162, 255, 181, 83, 65, 249, 59, 177, 236, 55, 114, 79, 65, 236, 171, 208, 79, 254, 181, 83, 65, 123, 78, 164, 8, 54, 114, 79, 65, 39, 79, 204, 141, 254, 181, 83, 65, 169, 70, 101, 80, 50, 114, 79, 65, 79, 202, 190, 73, 255, 181, 83, 65, 112, 191, 224, 197, 47, 114, ...]

===== eurocrops =====
  nuts original_code            original_name          translated_name  hcat4_code           hcat4_name  usage_code           usage_name
0   at         10001          NICHT DEFINIERT              not defined  3390000000  not_known_and_other           0     No specified use
1   at           105               KÖRNERMAIS               GRAIN CORN  3310106000   maize_corn_popcorn           6  Harvested as Grains
2   at           106  MAIS CORN-COB-MIX (CCM)  CORN CORN-COB-MIX (CCM)  3310106000   maize_corn_popcorn           0     No specified use
3   at           107               ZUCKERMAIS               SUGAR CORN  3310106000   maize_corn_popcorn           0     No specified use
4   at           109                 SILOMAIS                SILO CORN  3310106000   maize_corn_popcorn           3        Fodder/Forage

===== hcat4 =====
   hcat4_code                hcat4_name  seasonality_code seasonality_name
0  3310000000              arable_crops                 0              NaN
1  3310100000                    cereal                 0              NaN
2  3310101000         common_soft_wheat                 0              NaN
3  3310101001  winter_common_soft_wheat                 1           winter
4  3310101002  spring_common_soft_wheat                 2           spring

===== hcat4_agriprod_mapping =====
   hcat4_code    hcat4_name  usage_code               usage_name link agriprod_code                                         agriprod_name
0  3310000000  arable_crops           0         No specified use    =           ARA                                           Arable land
1  3310000000  arable_crops           2  Industry/for processing    =           ARA                                           Arable land
2  3310000000  arable_crops           3            Fodder/Forage    =           FOP                                         Forage plants
3  3310000000  arable_crops           9         Seed/Propagation    <         E0000                                   Seeds and seedlings
4  3310100000        cereal           0         No specified use    =         C0000  Cereals for the production of grain (including seed)

===== hcat4_hrl_mapping =====
   hcat4_code                hcat4_name  hrl_code                  hrl_name
0  3310000000              arable_crops      3100  Unclassified arable crop
1  3310100000                    cereal      1150             Other Cereals
2  3310101000         common_soft_wheat      1110                     Wheat
3  3310101001  winter_common_soft_wheat      1110                     Wheat
4  3310101002  spring_common_soft_wheat      1110                     Wheat

Creating macro in order to join every table so that i get all the possible informations, work on them, see what i need to save, save it and then go to the next table and so on and so forth

   cropfield original_code    off_id  off_area    area_ha  \
0     143411         10199  19606262      7.50   7.500565
1      96306         10257  18380291     49.07  49.078180
2      96388         10257  18395789     36.07  36.075260
3      99580         10199  18211860      0.78   0.776068
4     153953         10257  19253861      4.52   4.516176

                                                geom  longitude  latitude  \
0  [1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ...  69.221697  3.691200
1  [1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 2, ...  70.518306  2.502901
2  [1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 2, ...  70.150675  2.220605
3  [1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ...  69.481556  2.450485
4  [1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ...  70.746065  1.254477

  nuts         original_name  ... usage_code        usage_name  \
0   ee            rohttaimed  ...          0  No specified use
1   ee  taliraps allakülvita  ...          8               Oil
2   ee  taliraps allakülvita  ...          8               Oil
3   ee            rohttaimed  ...          0  No specified use
4   ee  taliraps allakülvita  ...          8               Oil

  seasonality_code  seasonality_name link  agriprod_code  \
0                0               NaN    <    J0000+G1000
1                1            winter    =          I1111
2                1            winter    =          I1111
3                0               NaN    <    J0000+G1000
4                1            winter    =          I1111

                                       agriprod_name hrl_code   hrl_name  \
0  Permanent grassland+Temporary grasses and graz...     4000  Grassland
1                  Winter rape and turnip rape seeds     1430   Rapeseed
2                  Winter rape and turnip rape seeds     1430   Rapeseed
3  Permanent grassland+Temporary grasses and graz...     4000  Grassland
4                  Winter rape and turnip rape seeds     1430   Rapeseed

          crop_category
0  Grassland and forage
1         Oilseed crops
2         Oilseed crops
3  Grassland and forage
4         Oilseed crops

[5 rows x 23 columns]
(175951, 23)

In [ ]:
conn.execute("CREATE MACRO IF NOT EXISTS bigquery() AS TABLE SELECT * FROM eurocrops " \
"INNER JOIN hcat4 on eurocrops.hcat4_code = hcat4.hcat4_code " \
"INNER JOIN hcat4_agriprod_mapping as hcat4_am on eurocrops.hcat4_code = hcat4_am.hcat4_code " \
"INNER JOIN hcat4_eagle_mapping as hcat4_em on eurocrops.hcat4_code = hcat4_em.hcat4_code " \
"INNER JOIN hcat4_hrl_mapping as hcat4_hrl on eurocrops.hcat4_code = hcat4_hrl.hcat4_code " \
"INNER JOIN agriprod_fadn_mapping as agfm on hcat4_am.agriprod_code = agfm.agriprod_code")

In [37]:
conn.execute("select * from bigquery()").fetch_df()

,nuts,original_code,original_name,translated_name,hcat4_code,hcat4_name,usage_code,usage_name,hcat4_code_1,hcat4_name_1,...,eagle_seasonality_code,eagle_seasonality_name,hcat4_code_4,hcat4_name_4,hrl_code,hrl_name,agriprod_code_1,agriprod_name_1,fadn_code,code_name
0,at,10001,NICHT DEFINIERT,not defined,3390000000,not_known_and_other,0,No specified use,3390000000,not_known_and_other,...,None,None,3390000000,not_known_and_other,0,Other,FA9,Other areas on the farms,None,None
1,at,105,KÖRNERMAIS,GRAIN CORN,3310106000,maize_corn_popcorn,6,Harvested as Grains,3310106000,maize_corn_popcorn,...,None,None,3310106000,maize_corn_popcorn,1130,Maize,C1500,Grain maize and corn-cob-mix,SE035,Cereals (ha)
2,at,106,MAIS CORN-COB-MIX (CCM),CORN CORN-COB-MIX (CCM),3310106000,maize_corn_popcorn,0,No specified use,3310106000,maize_corn_popcorn,...,None,None,3310106000,maize_corn_popcorn,1130,Maize,C1500,Grain maize and corn-cob-mix,SE035,Cereals (ha)
3,at,107,ZUCKERMAIS,SUGAR CORN,3310106000,maize_corn_popcorn,0,No specified use,3310106000,maize_corn_popcorn,...,None,None,3310106000,maize_corn_popcorn,1130,Maize,C1500,Grain maize and corn-cob-mix,SE035,Cereals (ha)
4,at,109,SILOMAIS,SILO CORN,3310106000,maize_corn_popcorn,3,Fodder/Forage,3310106000,maize_corn_popcorn,...,None,None,3310106000,maize_corn_popcorn,1130,Maize,C1500,Grain maize and corn-cob-mix,SE035,Cereals (ha)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15109,sk,10152,Pôda ležiaca úhorom s porastom,Fallen land with vegetation,3311100000,fallow_land_not_crop,0,No specified use,3311100000,fallow_land_not_crop,...,None,None,3311100000,fallow_land_not_crop,3100,Unclassified arable crop,Q0000,Fallow land,SE073,Set aside (ha)
15110,sk,10153,Pôda ležiaca úhorom s produkciou bez hnojenia,Fallow land with production without fertilization,3311100000,fallow_land_not_crop,0,No specified use,3311100000,fallow_land_not_crop,...,None,None,3311100000,fallow_land_not_crop,3100,Unclassified arable crop,Q0000,Fallow land,SE073,Set aside (ha)
15111,sk,10154,Pôda ležiaca úhorom s produkciou s hnojením,Fallow land with production and fertilization,3311100000,fallow_land_not_crop,0,No specified use,3311100000,fallow_land_not_crop,...,None,None,3311100000,fallow_land_not_crop,3100,Unclassified arable crop,Q0000,Fallow land,SE073,Set aside (ha)
15112,sk,10197,Strukovinovo-obilná miešanka,Legume-cereal mixer,3310200000,legumes,0,No specified use,3310200000,legumes,...,None,None,3310200000,legumes,1220,Dry Pulses,P0000,Dry pulses and protein crops for the productio...,SE041,Other field crops (ha)
15113,sk,10198,Strukovinovo-olejná miešanka,Legume-oil mixer,3310200000,legumes,8,Oil,3310200000,legumes,...,None,None,3310200000,legumes,1220,Dry Pulses,P0000,Dry pulses and protein crops for the productio...,SE041,Other field crops (ha)

In [38]:
at_2020 = conn.execute("select * from at_2020").fetch_df()

In [41]:
at_2020

,cropfield,original_code,off_id,off_area,area_ha,geom
0,2014349,751,83804969.0,3.131537,3.132349,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
1,2023764,751,83313100.0,0.713712,0.714132,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
2,2014837,751,83849727.0,0.615037,0.615360,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
3,968090,990,83512713.0,1.864932,1.865935,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
4,968091,990,83512713.0,0.102825,0.102880,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
...,...,...,...,...,...,...
2614615,425508,636,84556125.0,0.246434,0.246575,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
2614616,425509,636,84556128.0,0.148929,0.149014,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
2614617,425510,636,84556118.0,0.103569,0.103629,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
2614618,425814,636,84599303.0,0.106638,0.106689,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
2614619,425856,636,84584534.0,0.349749,0.349931,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 2, ..."

In [11]:
dd = conn.execute("select * from bigquery()").fetch_df()

CatalogException: Catalog Error: Table Function with name bigquery does not exist!
Did you mean "query"?

LINE 1: select * from bigquery()
                      ^

In [33]:
dd['original_code'].values

array(['10001', '105', '106', ..., '10154', '10197', '10198'],
      shape=(15114,), dtype=object)

In [ ]:
print(at_2020["original_code"].dtype)
print(dd["original_code"].dtype)
print(dd.index.dtype)

In [40]:
print(dd.columns.values)
print(at_2020.columns.values)

['nuts' 'original_code' 'original_name' 'translated_name' 'hcat4_code'
 'hcat4_name' 'usage_code' 'usage_name' 'hcat4_code_1' 'hcat4_name_1'
 'seasonality_code' 'seasonality_name' 'hcat4_code_2' 'hcat4_name_2'
 'usage_code_1' 'usage_name_1' 'link' 'agriprod_code' 'agriprod_name'
 'hcat4_code_3' 'hcat4_name_3' 'link_1' 'eagle_code' 'eagle_name'
 'eagle_seasonality_code' 'eagle_seasonality_name' 'hcat4_code_4'
 'hcat4_name_4' 'hrl_code' 'hrl_name' 'agriprod_code_1' 'agriprod_name_1'
 'fadn_code' 'code_name']
['cropfield' 'original_code' 'off_id' 'off_area' 'area_ha' 'geom']

In [34]:
result = at_2020.merge(
    dd,
    on="original_code",
    how="left"
)

In [39]:
len(dd), dd["original_code"].nunique()

(15114, 2347)

In [35]:
result

,cropfield,original_code,off_id,off_area,area_ha,geom,nuts,original_name,translated_name,hcat4_code,...,eagle_seasonality_code,eagle_seasonality_name,hcat4_code_4,hcat4_name_4,hrl_code,hrl_name,agriprod_code_1,agriprod_name_1,fadn_code,code_name
0,2014349,751,83804969.0,3.131537,3.132349,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ...",at,ÖLKÜRBISSE,Oil pumpkins,3310702040,...,None,None,3310702040,pumpkin_squash_gourd,1210,Fresh Vegetables,E0000,Seeds and seedlings,None,None
1,2014349,751,83804969.0,3.131537,3.132349,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ...",dea,Rhodiola (Rosenwurz),Rhodiola (rose root),3310612990,...,None,None,3310612990,other_aromatic_medicinal_culinary_plants_spice...,1210,Fresh Vegetables,I5000,"Aromatic, medicinal and culinary plants",SE041,Other field crops (ha)
2,2014349,751,83804969.0,3.131537,3.132349,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ...",at,ÖLKÜRBISSE,Oil pumpkins,3310702040,...,None,None,3310702040,pumpkin_squash_gourd,1210,Fresh Vegetables,I1190,Other oilseed crops n.e.c.,SE041,Other field crops (ha)
3,2014349,751,83804969.0,3.131537,3.132349,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ...",at,ÖLKÜRBISSE,Oil pumpkins,3310702040,...,None,None,3310702040,pumpkin_squash_gourd,1210,Fresh Vegetables,V3430,Gourds and pumpkins,SE046,Vegetables and flowers (ha)
4,2014349,751,83804969.0,3.131537,3.132349,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ...",at,ÖLKÜRBISSE,Oil pumpkins,3310702040,...,None,None,3310702040,pumpkin_squash_gourd,1210,Fresh Vegetables,V3430,Gourds and pumpkins,SE046,Vegetables and flowers (ha)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25139681,425856,636,84584534.0,0.349749,0.349931,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 2, ...",be2,Engels raaigras,perennial ryegrass,3320201050,...,None,None,3320201050,lolium_ryegrass,4100,Temporary Grassland,G1000,Temporary grasses and grazings,SE071,Forage crops (ha)
25139682,425856,636,84584534.0,0.349749,0.349931,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 2, ...",de4,Feldsalat/Ackersalat/Rapunzel,Lamb's lettuce / field lettuce / Rapunzel,3310717040,...,None,None,3310717040,lambs_lettuce_rapunzel,1210,Fresh Vegetables,V2900,Other leafy or stalked vegetables n.e.c.,SE046,Vegetables and flowers (ha)
25139683,425856,636,84584534.0,0.349749,0.349931,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 2, ...",dea,Feldsalate (auch Rapunzel),Lamb's lettuce (also Rapunzel),3310717040,...,None,None,3310717040,lambs_lettuce_rapunzel,1210,Fresh Vegetables,V2900,Other leafy or stalked vegetables n.e.c.,SE046,Vegetables and flowers (ha)
25139684,425856,636,84584534.0,0.349749,0.349931,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 2, ...",at,WECHSELWIESE,Rotational pasture or meadow.,3320200000,...,None,None,3320200000,temporary_grassland,4100,Temporary Grassland,G1000,Temporary grasses and grazings,SE071,Forage crops (ha)
25139685,425856,636,84584534.0,0.349749,0.349931,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 2, ...",nl,Saffloer,safflower,3310839000,...,None,None,3310839000,safflower,1210,Fresh Vegetables,N0000,Flowers and ornamental plants (excluding nurse...,SE046,Vegetables and flowers (ha)

In [36]:
at_2020

,cropfield,original_code,off_id,off_area,area_ha,geom
0,2014349,751,83804969.0,3.131537,3.132349,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
1,2023764,751,83313100.0,0.713712,0.714132,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
2,2014837,751,83849727.0,0.615037,0.615360,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
3,968090,990,83512713.0,1.864932,1.865935,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
4,968091,990,83512713.0,0.102825,0.102880,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
...,...,...,...,...,...,...
2614615,425508,636,84556125.0,0.246434,0.246575,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
2614616,425509,636,84556128.0,0.148929,0.149014,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
2614617,425510,636,84556118.0,0.103569,0.103629,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
2614618,425814,636,84599303.0,0.106638,0.106689,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 1, ..."
2614619,425856,636,84584534.0,0.349749,0.349931,"[1, 6, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 2, ..."

In [ ]:
conn.execute("SHOW databases").fetch_df()

In [ ]:
conn.execute("SELECT * FROM agriprod_fadn_mapping").fetch_df()

In [ ]:

conn.execute("SET enable_geoparquet_conversion = false;")


test = conn.execute("SET enable_geoparquet_conversion = false; SELECT * FROM eurocrops " \
"INNER JOIN hcat4 on eurocrops.hcat4_code = hcat4.hcat4_code " \
"INNER JOIN hcat4_agriprod_mapping as hcat4_am on eurocrops.hcat4_code = hcat4_am.hcat4_code " \
"INNER JOIN hcat4_eagle_mapping as hcat4_em on eurocrops.hcat4_code = hcat4_em.hcat4_code " \
"INNER JOIN hcat4_hrl_mapping as hcat4_hrl on eurocrops.hcat4_code = hcat4_hrl.hcat4_code " \
"INNER JOIN agriprod_fadn_mapping as agfm on hcat4_am.agriprod_code = agfm.agriprod_code").fetch_df()

In [ ]:
test

In [ ]:
test.columns.values

In [ ]:
conn = duckdb.connect(global_config.paths["duckdbpath"])

tables = conn.execute("SHOW TABLES").fetchdf()
print(tables)

In [ ]:
conn_shady = duckdb.connect('/home/wr3nch/Documents/Projects/RSSIA/dataset/exported/eurocropsv2.duckdb')

conn_shady.execute("SHOW TABLES").fetch_df()

In [ ]:
import duckdb

file_path = (
    "/home/wr3nch/Documents/Projects/RSSIA/"
    "dataset/at_2020.parquet"
)

conn = duckdb.connect()

conn.execute("SET enable_geoparquet_conversion = false;")

df = conn.execute("""
    SELECT *
    FROM read_parquet(?)
    LIMIT 10
""", [file_path]).fetchdf()

df

In [ ]:
db = "eurocropsv2"

tables = conn.execute(f"""
    SELECT table_schema, table_name
    FROM information_schema.tables
    WHERE table_catalog = '{db}'
      AND table_type = 'BASE TABLE'
    ORDER BY table_schema, table_name
""").fetchall()

tables

In [ ]:
def quote(name):
    return '"' + name.replace('"', '""') + '"'


queries = []

for schema, table in tables:
    queries.append(f"""
        SELECT
            *,
            '{schema}.{table}' AS source_table
        FROM {quote(db)}.{quote(schema)}.{quote(table)}
    """)

sql = "\nUNION ALL BY NAME\n".join(queries)

print(sql)

In [ ]:
df = conn.execute(sql).fetch_df()

# AI Generated code
This section contains ai generated code because i don't get how the geometry (lat and long) is not loaded by their scripts but it is actually present in the parquet files.

In [ ]:
from pathlib import Path
import duckdb
import pandas as pd


# ------------------------------------------------------------------
# 1. Paths and table name
# ------------------------------------------------------------------

parquet_path = Path(
    "/home/wr3nch/Documents/Projects/RSSIA/dataset/at_2020.parquet"
)

duckdb_path = Path(
    "/home/wr3nch/Documents/Projects/RSSIA/dataset/eurocrops.duckdb"
)

table_name = "at_2020"


# ------------------------------------------------------------------
# 2. Validate paths
# ------------------------------------------------------------------

if not parquet_path.exists():
    raise FileNotFoundError(
        f"Parquet file does not exist:\n{parquet_path}"
    )

duckdb_path.parent.mkdir(parents=True, exist_ok=True)

print("Parquet file:", parquet_path)
print("DuckDB file:", duckdb_path)
print("DuckDB table:", table_name)


# ------------------------------------------------------------------
# 3. Open DuckDB
# ------------------------------------------------------------------

conn = duckdb.connect(str(duckdb_path))


# ------------------------------------------------------------------
# 4. Load the spatial extension
# ------------------------------------------------------------------

try:
    conn.execute("LOAD spatial")
except duckdb.Error:
    # INSTALL requires internet only if the extension is not already installed.
    conn.execute("INSTALL spatial")
    conn.execute("LOAD spatial")


# ------------------------------------------------------------------
# 5. Disable automatic GeoParquet conversion
#
# The EuroCropsV2 files can contain incomplete GeoParquet metadata.
# With conversion disabled, geometry is read as raw WKB/BLOB.
# ------------------------------------------------------------------

conn.execute("""
    SET enable_geoparquet_conversion = false
""")


# ------------------------------------------------------------------
# 6. Inspect the raw Parquet schema
# ------------------------------------------------------------------

raw_schema = conn.execute(
    """
    DESCRIBE
    SELECT *
    FROM read_parquet(?)
    """,
    [str(parquet_path)],
).fetchdf()

print("\nRaw Parquet schema:")
display(raw_schema)


# ------------------------------------------------------------------
# 7. Verify that the geometry column exists
# ------------------------------------------------------------------

raw_columns = set(raw_schema["column_name"].str.lower())

if "geometry" not in raw_columns:
    raise RuntimeError(
        "The Parquet file does not contain a column named 'geometry'. "
        f"Available columns: {sorted(raw_columns)}"
    )


# ------------------------------------------------------------------
# 8. Import the Parquet file into DuckDB
# ------------------------------------------------------------------

conn.execute(
    f"""
    CREATE OR REPLACE TABLE "{table_name}" AS
    SELECT *
    FROM read_parquet(?)
    """,
    [str(parquet_path)],
)

print(f"\nImported {parquet_path.name} into table {table_name!r}")


# ------------------------------------------------------------------
# 9. Convert raw WKB geometry to DuckDB GEOMETRY
# ------------------------------------------------------------------

conn.execute(
    f"""
    ALTER TABLE "{table_name}"
    ADD COLUMN geom GEOMETRY
    """
)

conn.execute(
    f"""
    UPDATE "{table_name}"
    SET geom = ST_GeomFromWKB(geometry)
    WHERE geometry IS NOT NULL
    """
)


# ------------------------------------------------------------------
# 10. Remove the original raw WKB column
#
# Comment this section out if you want to preserve both geometry and geom.
# ------------------------------------------------------------------

conn.execute(
    f"""
    ALTER TABLE "{table_name}"
    DROP COLUMN geometry
    """
)


# ------------------------------------------------------------------
# 11. Create a spatial index
# ------------------------------------------------------------------

conn.execute(
    f"""
    CREATE INDEX IF NOT EXISTS "{table_name}_geom_rtree"
    ON "{table_name}"
    USING RTREE (geom)
    """
)


# ------------------------------------------------------------------
# 12. Verify the imported table
# ------------------------------------------------------------------

imported_schema = conn.execute(
    f'DESCRIBE "{table_name}"'
).fetchdf()

print("\nImported DuckDB schema:")
display(imported_schema)

row_count = conn.execute(
    f'SELECT COUNT(*) FROM "{table_name}"'
).fetchone()[0]

geometry_count = conn.execute(
    f"""
    SELECT COUNT(*)
    FROM "{table_name}"
    WHERE geom IS NOT NULL
    """
).fetchone()[0]

print("\nTotal rows:", row_count)
print("Rows with geometry:", geometry_count)


# ------------------------------------------------------------------
# 13. Check geometry types
# ------------------------------------------------------------------

geometry_types = conn.execute(
    f"""
    SELECT
        ST_GeometryType(geom) AS geometry_type,
        COUNT(*) AS row_count
    FROM "{table_name}"
    WHERE geom IS NOT NULL
    GROUP BY ST_GeometryType(geom)
    ORDER BY row_count DESC
    """
).fetchdf()

print("\nGeometry types:")
display(geometry_types)


# ------------------------------------------------------------------
# 14. Derive longitude and latitude
#
# EuroCropsV2 geometry is expected to use EPSG:3035.
#
# ST_PointOnSurface returns a representative point guaranteed to lie
# inside the parcel. The point is then transformed to EPSG:4326.
#
# X = longitude
# Y = latitude
# ------------------------------------------------------------------

coordinate_query = f"""
WITH representative_points AS (
    SELECT
        *,
        ST_PointOnSurface(geom) AS point_3035
    FROM "{table_name}"
    WHERE geom IS NOT NULL
),

wgs84_points AS (
    SELECT
        *,
        ST_Transform(
            point_3035,
            'EPSG:3035',
            'EPSG:4326',
            always_xy := true
        ) AS point_wgs84
    FROM representative_points
)

SELECT
    * EXCLUDE (point_3035, point_wgs84),

    ST_X(point_wgs84) AS longitude,
    ST_Y(point_wgs84) AS latitude

FROM wgs84_points
"""

df = conn.execute(coordinate_query).fetchdf()


# ------------------------------------------------------------------
# 15. Inspect the resulting Pandas DataFrame
# ------------------------------------------------------------------

print("\nDataFrame shape:", df.shape)
display(df.head())

print("\nCoordinate sample:")
display(
    df[["longitude", "latitude"]]
    .dropna()
    .head(10)
)


# ------------------------------------------------------------------
# 16. Basic coordinate sanity check
# ------------------------------------------------------------------

invalid_coordinates = df[
    ~df["longitude"].between(-180, 180)
    | ~df["latitude"].between(-90, 90)
]

print("\nRows with invalid longitude/latitude:", len(invalid_coordinates))


# ------------------------------------------------------------------
# 17. Optional: export the result to Parquet
# ------------------------------------------------------------------

output_path = parquet_path.with_name("at_2020_with_coordinates.parquet")

conn.execute(
    f"""
    COPY (
        {coordinate_query}
    )
    TO ?
    (
        FORMAT PARQUET,
        COMPRESSION ZSTD
    )
    """,
    [str(output_path)],
)

print("\nOutput written to:", output_path)


# ------------------------------------------------------------------
# 18. Show all tables currently in the DuckDB database
# ------------------------------------------------------------------

print("\nDuckDB tables:")
display(conn.execute("SHOW TABLES").fetchdf())


# Close only when you have finished querying the database.
# conn.close()